### BOARD_TAG
### It must be set to the board you are currently using. (i.e uno, mega2560, etc.)
BOARD_TAG = nano
BOARD_SUB = atmega328

OPTIMIZATION_LEVEL = s

### ARDUINO_LIBS
### Arduino libraries
ARDUINO_LIBS = \
	Adafruit_GFX \
	Adafruit_PCD8544 \
	Buttons \
	SimpleTimer \
	PinChangeInt \
	EEPROM \
	SPI

include Arduino.mk
