### BOARD_TAG
### It must be set to the board you are currently using. (i.e uno, mega2560, etc.)
BOARD_TAG = nano328

OPTIMIZATION_LEVEL = 3

### ARDUINO_LIBS
### Arduino libraries
ARDUINO_LIBS = \
	Adafruit_GFX \
	Adafruit_PCD8544 \
	Buttons \
	LCD_5110_SPI \
	LiquidCrystal \
	SoftwareSerial \
	SimpleTimer \
	EEPROM \
	SPI

include Arduino.mk
